# ---
# - name: Add an Apt signing key, uses whichever key is at the URL
#   apt_key:
#     url: curl -fsSL https://download.docker.com/linux/ubuntu/gpg
#     state: present
#   become: yes

# - name: Update repositories cache and install "foo" package
#   apt:
#     name: apt-get
#     update_cache: yes
#   become: yes

# - apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
#     state: present
#   become: yes

# - name: Install the package "foo"
#   apt:
#     name: docker-ce

# - name: assure docker is installed
#   apt: 
#     name: docker.io 
#     state: installed